extends:
  - stylelint-config-standard
  - stylelint-config-prettier
rules:
  color-function-notation: legacy
  alpha-value-notation: null
  hue-degree-notation: null
  selector-class-pattern: ^[a-zA-Z]([a-zA-Z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$
